import 'korea_region.dart';

const List<KoreaRegion> chungbukRegions = [
  // ===== 시 =====
  KoreaRegion(
    id: "KR_CB_CHEONGJU",
    name: "청주",
    province: "충청북도",
    type: KoreaRegionType.city,
    lat: 36.6424,
    lng: 127.4890,
    mapRegionId: "KR_CB_CHEONGJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CB_CHUNGJU",
    name: "충주",
    province: "충청북도",
    type: KoreaRegionType.city,
    lat: 36.9910,
    lng: 127.9259,
    mapRegionId: "KR_CB_CHUNGJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CB_JECHEON",
    name: "제천",
    province: "충청북도",
    type: KoreaRegionType.city,
    lat: 37.1326,
    lng: 128.1910,
    mapRegionId: "KR_CB_JECHEON",
    mapRegionType: MapRegionType.city,
  ),

  // ===== 군 =====
  KoreaRegion(
    id: "KR_CB_BOEUN",
    name: "보은",
    province: "충청북도",
    type: KoreaRegionType.county,
    lat: 36.4895,
    lng: 127.7293,
    mapRegionId: "KR_CB_BOEUN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CB_OKCHEON",
    name: "옥천",
    province: "충청북도",
    type: KoreaRegionType.county,
    lat: 36.3065,
    lng: 127.5736,
    mapRegionId: "KR_CB_OKCHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CB_YEONGDONG",
    name: "영동",
    province: "충청북도",
    type: KoreaRegionType.county,
    lat: 36.1751,
    lng: 127.7768,
    mapRegionId: "KR_CB_YEONGDONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CB_JEUNGPYEONG",
    name: "증평",
    province: "충청북도",
    type: KoreaRegionType.county,
    lat: 36.7847,
    lng: 127.5815,
    mapRegionId: "KR_CB_JEUNGPYEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CB_JINCHEON",
    name: "진천",
    province: "충청북도",
    type: KoreaRegionType.county,
    lat: 36.8561,
    lng: 127.4359,
    mapRegionId: "KR_CB_JINCHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CB_GOESAN",
    name: "괴산",
    province: "충청북도",
    type: KoreaRegionType.county,
    lat: 36.8121,
    lng: 127.7947,
    mapRegionId: "KR_CB_GOESAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CB_EUMSEONG",
    name: "음성",
    province: "충청북도",
    type: KoreaRegionType.county,
    lat: 36.9397,
    lng: 127.6907,
    mapRegionId: "KR_CB_EUMSEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CB_DANYANG",
    name: "단양",
    province: "충청북도",
    type: KoreaRegionType.county,
    lat: 36.9846,
    lng: 128.3659,
    mapRegionId: "KR_CB_DANYANG",
    mapRegionType: MapRegionType.city,
  ),
];
