import 'korea_region.dart';

const List<KoreaRegion> chungnamRegions = [
  // ===== 시 =====
  KoreaRegion(
    id: "KR_CN_CHEONAN",
    name: "천안",
    nameEn: "CHEONAN",
    province: "충청남도",
    type: KoreaRegionType.city,
    lat: 36.8151,
    lng: 127.1139,
    mapRegionId: "KR_CN_CHEONAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_GONGJU",
    name: "공주",
    nameEn: "GONGJU",
    province: "충청남도",
    type: KoreaRegionType.city,
    lat: 36.4556,
    lng: 127.1246,
    mapRegionId: "KR_CN_GONGJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_BORYEONG",
    name: "보령",
    nameEn: "BORYEONG",
    province: "충청남도",
    type: KoreaRegionType.city,
    lat: 36.3494,
    lng: 126.5977,
    mapRegionId: "KR_CN_BORYEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_ASAN",
    name: "아산",
    nameEn: "ASAN",
    province: "충청남도",
    type: KoreaRegionType.city,
    lat: 36.7899,
    lng: 127.0017,
    mapRegionId: "KR_CN_ASAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_SEOSAN",
    name: "서산",
    nameEn: "SEOSAN",
    province: "충청남도",
    type: KoreaRegionType.city,
    lat: 36.7845,
    lng: 126.4503,
    mapRegionId: "KR_CN_SEOSAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_NONSAN",
    name: "논산",
    nameEn: "NONSAN",
    province: "충청남도",
    type: KoreaRegionType.city,
    lat: 36.1872,
    lng: 127.0989,
    mapRegionId: "KR_CN_NONSAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_GYERYONG",
    name: "계룡",
    nameEn: "GYERYONG",
    province: "충청남도",
    type: KoreaRegionType.city,
    lat: 36.2746,
    lng: 127.2487,
    mapRegionId: "KR_CN_GYERYONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_DANGJIN",
    name: "당진",
    nameEn: "DANGJIN",
    province: "충청남도",
    type: KoreaRegionType.city,
    lat: 36.8895,
    lng: 126.6458,
    mapRegionId: "KR_CN_DANGJIN",
    mapRegionType: MapRegionType.city,
  ),

  // ===== 군 =====
  KoreaRegion(
    id: "KR_CN_GEUMSAN",
    name: "금산",
    nameEn: "GEUMSAN",
    province: "충청남도",
    type: KoreaRegionType.county,
    lat: 36.1036,
    lng: 127.4889,
    mapRegionId: "KR_CN_GEUMSAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_BUYEO",
    name: "부여",
    nameEn: "BUYEO",
    province: "충청남도",
    type: KoreaRegionType.county,
    lat: 36.2756,
    lng: 126.9098,
    mapRegionId: "KR_CN_BUYEO",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_SEOCHEON",
    name: "서천",
    nameEn: "SEOCHEON",
    province: "충청남도",
    type: KoreaRegionType.county,
    lat: 36.0803,
    lng: 126.6916,
    mapRegionId: "KR_CN_SEOCHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_CHEONGYANG",
    name: "청양",
    nameEn: "CHEONGYANG",
    province: "충청남도",
    type: KoreaRegionType.county,
    lat: 36.4593,
    lng: 126.8020,
    mapRegionId: "KR_CN_CHEONGYANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_HONGSEONG",
    name: "홍성",
    nameEn: "HONGSEONG",
    province: "충청남도",
    type: KoreaRegionType.county,
    lat: 36.6013,
    lng: 126.6608,
    mapRegionId: "KR_CN_HONGSEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_YESAN",
    name: "예산",
    nameEn: "YESAN",
    province: "충청남도",
    type: KoreaRegionType.county,
    lat: 36.6823,
    lng: 126.8489,
    mapRegionId: "KR_CN_YESAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_CN_TAEAN",
    name: "태안",
    nameEn: "TAEAN",
    province: "충청남도",
    type: KoreaRegionType.county,
    lat: 36.7455,
    lng: 126.2983,
    mapRegionId: "KR_CN_TAEAN",
    mapRegionType: MapRegionType.city,
  ),
];
