import 'korea_region.dart';

const List<KoreaRegion> gangwonRegions = [
  // ===== 시 =====
  KoreaRegion(
    id: "KR_GW_CHUNCHEON",
    name: "춘천",
    nameEn: "CHUNCHEON",
    province: "강원특별자치도",
    type: KoreaRegionType.city,
    lat: 37.8813,
    lng: 127.7298,
    mapRegionId: "KR_GW_CHUNCHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_WONJU",
    name: "원주",
    nameEn: "WONJU",
    province: "강원특별자치도",
    type: KoreaRegionType.city,
    lat: 37.3422,
    lng: 127.9202,
    mapRegionId: "KR_GW_WONJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_GANGNEUNG",
    name: "강릉",
    nameEn: "GANGNEUNG",
    province: "강원특별자치도",
    type: KoreaRegionType.city,
    lat: 37.7519,
    lng: 128.8761,
    mapRegionId: "KR_GW_GANGNEUNG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_DONGHAE",
    name: "동해",
    nameEn: "DONGHAE",
    province: "강원특별자치도",
    type: KoreaRegionType.city,
    lat: 37.5247,
    lng: 129.1143,
    mapRegionId: "KR_GW_DONGHAE",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_TAEBAEK",
    name: "태백",
    nameEn: "TAEBAEK",
    province: "강원특별자치도",
    type: KoreaRegionType.city,
    lat: 37.1641,
    lng: 128.9856,
    mapRegionId: "KR_GW_TAEBAEK",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_SOKCHO",
    name: "속초",
    nameEn: "SOKCHO",
    province: "강원특별자치도",
    type: KoreaRegionType.city,
    lat: 38.2070,
    lng: 128.5919,
    mapRegionId: "KR_GW_SOKCHO",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_SAMCHEOK",
    name: "삼척",
    nameEn: "SAMCHEOK",
    province: "강원특별자치도",
    type: KoreaRegionType.city,
    lat: 37.4499,
    lng: 129.1651,
    mapRegionId: "KR_GW_SAMCHEOK",
    mapRegionType: MapRegionType.city,
  ),

  // ===== 군 =====
  KoreaRegion(
    id: "KR_GW_HONGCHEON",
    name: "홍천",
    nameEn: "HONGCHEON",
    province: "강원특별자치도",
    type: KoreaRegionType.county,
    lat: 37.6911,
    lng: 127.8857,
    mapRegionId: "KR_GW_HONGCHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_HOENGSEONG",
    name: "횡성",
    nameEn: "HOENGSEONG",
    province: "강원특별자치도",
    type: KoreaRegionType.county,
    lat: 37.4917,
    lng: 127.9850,
    mapRegionId: "KR_GW_HOENGSEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_YEONGWOL",
    name: "영월",
    nameEn: "YEONGWOL",
    province: "강원특별자치도",
    type: KoreaRegionType.county,
    lat: 37.1835,
    lng: 128.4616,
    mapRegionId: "KR_GW_YEONGWOL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_PYEONGCHANG",
    name: "평창",
    nameEn: "PYEONGCHANG",
    province: "강원특별자치도",
    type: KoreaRegionType.county,
    lat: 37.3704,
    lng: 128.3907,
    mapRegionId: "KR_GW_PYEONGCHANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_JEONGSEON",
    name: "정선",
    nameEn: "JEONGSEON",
    province: "강원특별자치도",
    type: KoreaRegionType.county,
    lat: 37.3795,
    lng: 128.6609,
    mapRegionId: "KR_GW_JEONGSEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_CHEORWON",
    name: "철원",
    nameEn: "CHEORWON",
    province: "강원특별자치도",
    type: KoreaRegionType.county,
    lat: 38.1466,
    lng: 127.3137,
    mapRegionId: "KR_GW_CHEORWON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_HWACHEON",
    name: "화천",
    nameEn: "HWACHEON",
    province: "강원특별자치도",
    type: KoreaRegionType.county,
    lat: 38.1066,
    lng: 127.7081,
    mapRegionId: "KR_GW_HWACHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_YANGGU",
    name: "양구",
    nameEn: "YANGGU",
    province: "강원특별자치도",
    type: KoreaRegionType.county,
    lat: 38.1099,
    lng: 127.9892,
    mapRegionId: "KR_GW_YANGGU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_INJE",
    name: "인제",
    nameEn: "INJE",
    province: "강원특별자치도",
    type: KoreaRegionType.county,
    lat: 38.0695,
    lng: 128.1705,
    mapRegionId: "KR_GW_INJE",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_GOSEONG",
    name: "고성",
    nameEn: "GOSEONG",
    province: "강원특별자치도",
    type: KoreaRegionType.county,
    lat: 38.3802,
    lng: 128.4676,
    mapRegionId: "KR_GW_GOSEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GW_YANGYANG",
    name: "양양",
    nameEn: "YANGYANG",
    province: "강원특별자치도",
    type: KoreaRegionType.county,
    lat: 38.0755,
    lng: 128.6191,
    mapRegionId: "KR_GW_YANGYANG",
    mapRegionType: MapRegionType.city,
  ),
];
