import 'korea_region.dart';

const List<KoreaRegion> gyeongbukRegions = [
  // ===== 시 =====
  KoreaRegion(
    id: "KR_GB_POHANG",
    name: "포항",
    province: "경상북도",
    type: KoreaRegionType.city,
    lat: 36.0190,
    lng: 129.3435,
    mapRegionId: "KR_GB_POHANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_GYEONGJU",
    name: "경주",
    province: "경상북도",
    type: KoreaRegionType.city,
    lat: 35.8562,
    lng: 129.2247,
    mapRegionId: "KR_GB_GYEONGJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_GUMI",
    name: "구미",
    province: "경상북도",
    type: KoreaRegionType.city,
    lat: 36.1195,
    lng: 128.3446,
    mapRegionId: "KR_GB_GUMI",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_GIMCHEON",
    name: "김천",
    province: "경상북도",
    type: KoreaRegionType.city,
    lat: 36.1397,
    lng: 128.1136,
    mapRegionId: "KR_GB_GIMCHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_ANDONG",
    name: "안동",
    province: "경상북도",
    type: KoreaRegionType.city,
    lat: 36.5684,
    lng: 128.7294,
    mapRegionId: "KR_GB_ANDONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_YEONGJU",
    name: "영주",
    province: "경상북도",
    type: KoreaRegionType.city,
    lat: 36.8057,
    lng: 128.6241,
    mapRegionId: "KR_GB_YEONGJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_YEONGCHEON",
    name: "영천",
    province: "경상북도",
    type: KoreaRegionType.city,
    lat: 35.9733,
    lng: 128.9386,
    mapRegionId: "KR_GB_YEONGCHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_SANGJU",
    name: "상주",
    province: "경상북도",
    type: KoreaRegionType.city,
    lat: 36.4109,
    lng: 128.1592,
    mapRegionId: "KR_GB_SANGJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_MUNGYEONG",
    name: "문경",
    province: "경상북도",
    type: KoreaRegionType.city,
    lat: 36.5866,
    lng: 128.1865,
    mapRegionId: "KR_GB_MUNGYEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_GYEONGSAN",
    name: "경산",
    province: "경상북도",
    type: KoreaRegionType.city,
    lat: 35.8251,
    lng: 128.7413,
    mapRegionId: "KR_GB_GYEONGSAN",
    mapRegionType: MapRegionType.city,
  ),

  // ===== 군 =====

  // ⭐ 울릉도 (특별 취급)
  KoreaRegion(
    id: "KR_GB_ULLEUNG",
    name: "울릉도",
    province: "경상북도",
    type: KoreaRegionType.county,
    lat: 37.4844,
    lng: 130.9057,
    mapRegionId: "KR_SPECIAL_ULLEUNG",
    mapRegionType: MapRegionType.special,
  ),

  KoreaRegion(
    id: "KR_GB_YEONGYANG",
    name: "영양",
    province: "경상북도",
    type: KoreaRegionType.county,
    lat: 36.6666,
    lng: 129.1124,
    mapRegionId: "KR_GB_YEONGYANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_CHEONGDO",
    name: "청도",
    province: "경상북도",
    type: KoreaRegionType.county,
    lat: 35.6473,
    lng: 128.7345,
    mapRegionId: "KR_GB_CHEONGDO",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_GORYEONG",
    name: "고령",
    province: "경상북도",
    type: KoreaRegionType.county,
    lat: 35.7266,
    lng: 128.2639,
    mapRegionId: "KR_GB_GORYEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_SEONGJU",
    name: "성주",
    province: "경상북도",
    type: KoreaRegionType.county,
    lat: 35.9196,
    lng: 128.2830,
    mapRegionId: "KR_GB_SEONGJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_CHILGOK",
    name: "칠곡",
    province: "경상북도",
    type: KoreaRegionType.county,
    lat: 35.9956,
    lng: 128.4015,
    mapRegionId: "KR_GB_CHILGOK",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_YECHEON",
    name: "예천",
    province: "경상북도",
    type: KoreaRegionType.county,
    lat: 36.6540,
    lng: 128.4522,
    mapRegionId: "KR_GB_YECHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_BONGHWA",
    name: "봉화",
    province: "경상북도",
    type: KoreaRegionType.county,
    lat: 36.8931,
    lng: 128.7326,
    mapRegionId: "KR_GB_BONGHWA",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_ULJIN",
    name: "울진",
    province: "경상북도",
    type: KoreaRegionType.county,
    lat: 36.9931,
    lng: 129.4003,
    mapRegionId: "KR_GB_ULJIN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_CHEONGSONG",
    name: "청송",
    province: "경상북도",
    type: KoreaRegionType.county,
    lat: 36.4334,
    lng: 129.0570,
    mapRegionId: "KR_GB_CHEONGSONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GB_UISUNG",
    name: "의성",
    province: "경상북도",
    type: KoreaRegionType.county,
    lat: 36.3526,
    lng: 128.6970,
    mapRegionId: "KR_GB_UISUNG",
    mapRegionType: MapRegionType.city,
  ),
];
