import 'korea_region.dart';

const List<KoreaRegion> gyeongnamRegions = [
  // ===== 시 =====
  KoreaRegion(
    id: "KR_GN_CHANGWON",
    name: "창원",
    nameEn: "CHANGWON",
    province: "경상남도",
    type: KoreaRegionType.city,
    lat: 35.2285,
    lng: 128.6811,
    mapRegionId: "KR_GN_CHANGWON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_JINJU",
    name: "진주",
    nameEn: "JINJU",
    province: "경상남도",
    type: KoreaRegionType.city,
    lat: 35.1796,
    lng: 128.1076,
    mapRegionId: "KR_GN_JINJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_TONGYEONG",
    name: "통영",
    nameEn: "TONGYEONG",
    province: "경상남도",
    type: KoreaRegionType.city,
    lat: 34.8544,
    lng: 128.4332,
    mapRegionId: "KR_GN_TONGYEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_SACHEON",
    name: "사천",
    nameEn: "SACHEON",
    province: "경상남도",
    type: KoreaRegionType.city,
    lat: 35.0036,
    lng: 128.0646,
    mapRegionId: "KR_GN_SACHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_GIMHAE",
    name: "김해",
    nameEn: "GIMHAE",
    province: "경상남도",
    type: KoreaRegionType.city,
    lat: 35.2284,
    lng: 128.8890,
    mapRegionId: "KR_GN_GIMHAE",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_MIRYANG",
    name: "밀양",
    nameEn: "MIRYANG",
    province: "경상남도",
    type: KoreaRegionType.city,
    lat: 35.5037,
    lng: 128.7464,
    mapRegionId: "KR_GN_MIRYANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_GEOJE",
    name: "거제",
    nameEn: "GEOJE",
    province: "경상남도",
    type: KoreaRegionType.city,
    lat: 34.8805,
    lng: 128.6211,
    mapRegionId: "KR_GN_GEOJE",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_YANGSAN",
    name: "양산",
    nameEn: "YANGSAN",
    province: "경상남도",
    type: KoreaRegionType.city,
    lat: 35.3350,
    lng: 129.0370,
    mapRegionId: "KR_GN_YANGSAN",
    mapRegionType: MapRegionType.city,
  ),

  // ===== 군 =====
  KoreaRegion(
    id: "KR_GN_UIRYEONG",
    name: "의령",
    nameEn: "UIRYEONG",
    province: "경상남도",
    type: KoreaRegionType.county,
    lat: 35.3197,
    lng: 128.2617,
    mapRegionId: "KR_GN_UIRYEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_HAMAN",
    name: "함안",
    nameEn: "HAMAN",
    province: "경상남도",
    type: KoreaRegionType.county,
    lat: 35.2726,
    lng: 128.4065,
    mapRegionId: "KR_GN_HAMAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_CHANGNYEONG",
    name: "창녕",
    nameEn: "CHANGNYEONG",
    province: "경상남도",
    type: KoreaRegionType.county,
    lat: 35.5446,
    lng: 128.4923,
    mapRegionId: "KR_GN_CHANGNYEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_GOSEONG",
    name: "고성",
    nameEn: "GOSEONG",
    province: "경상남도",
    type: KoreaRegionType.county,
    lat: 34.9730,
    lng: 128.3237,
    mapRegionId: "KR_GN_GOSEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_NAMHAE",
    name: "남해",
    nameEn: "NAMHAE",
    province: "경상남도",
    type: KoreaRegionType.county,
    lat: 34.8370,
    lng: 127.8925,
    mapRegionId: "KR_GN_NAMHAE",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_HADONG",
    name: "하동",
    nameEn: "HADONG",
    province: "경상남도",
    type: KoreaRegionType.county,
    lat: 35.0673,
    lng: 127.7513,
    mapRegionId: "KR_GN_HADONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_SANCHEONG",
    name: "산청",
    nameEn: "SANCHEONG",
    province: "경상남도",
    type: KoreaRegionType.county,
    lat: 35.4154,
    lng: 127.8735,
    mapRegionId: "KR_GN_SANCHEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_HAMYANG",
    name: "함양",
    nameEn: "HAMYANG",
    province: "경상남도",
    type: KoreaRegionType.county,
    lat: 35.5204,
    lng: 127.7252,
    mapRegionId: "KR_GN_HAMYANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_GEOCHANG",
    name: "거창",
    nameEn: "GEOCHANG",
    province: "경상남도",
    type: KoreaRegionType.county,
    lat: 35.6866,
    lng: 127.9090,
    mapRegionId: "KR_GN_GEOCHANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GN_HAPCHEON",
    name: "합천",
    nameEn: "HAPCHEON",
    province: "경상남도",
    type: KoreaRegionType.county,
    lat: 35.5666,
    lng: 128.1658,
    mapRegionId: "KR_GN_HAPCHEON",
    mapRegionType: MapRegionType.city,
  ),
];
