import 'korea_region.dart';

const List<KoreaRegion> gyeonggiRegions = [
  // ===== 시 =====
  KoreaRegion(
    id: "KR_GG_SUWON",
    name: "수원",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.2636,
    lng: 127.0286,
    mapRegionId: "KR_GG_SUWON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_SEONGNAM",
    name: "성남",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.4200,
    lng: 127.1265,
    mapRegionId: "KR_GG_SEONGNAM",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_GOYANG",
    name: "고양",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.6584,
    lng: 126.8320,
    mapRegionId: "KR_GG_GOYANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_YONGIN",
    name: "용인",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.2411,
    lng: 127.1776,
    mapRegionId: "KR_GG_YONGIN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_BUCHEON",
    name: "부천",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.5035,
    lng: 126.7660,
    mapRegionId: "KR_GG_BUCHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_ANSAN",
    name: "안산",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.3219,
    lng: 126.8309,
    mapRegionId: "KR_GG_ANSAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_ANYANG",
    name: "안양",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.3943,
    lng: 126.9568,
    mapRegionId: "KR_GG_ANYANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_HWASEONG",
    name: "화성",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.1995,
    lng: 126.8310,
    mapRegionId: "KR_GG_HWASEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_PYEONGTAEK",
    name: "평택",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 36.9921,
    lng: 127.1126,
    mapRegionId: "KR_GG_PYEONGTAEK",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_UIJEONGBU",
    name: "의정부",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.7381,
    lng: 127.0337,
    mapRegionId: "KR_GG_UIJEONGBU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_SIHEUNG",
    name: "시흥",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.3799,
    lng: 126.8031,
    mapRegionId: "KR_GG_SIHEUNG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_GIMPO",
    name: "김포",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.6152,
    lng: 126.7158,
    mapRegionId: "KR_GG_GIMPO",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_PAJU",
    name: "파주",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.7599,
    lng: 126.7800,
    mapRegionId: "KR_GG_PAJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_GWANGMYEONG",
    name: "광명",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.4786,
    lng: 126.8645,
    mapRegionId: "KR_GG_GWANGMYEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_GUNPO",
    name: "군포",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.3616,
    lng: 126.9352,
    mapRegionId: "KR_GG_GUNPO",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_GWANGJU",
    name: "광주",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.4294,
    lng: 127.2551,
    mapRegionId: "KR_GG_GWANGJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_GURI",
    name: "구리",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.5943,
    lng: 127.1296,
    mapRegionId: "KR_GG_GURI",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_NAMYANGJU",
    name: "남양주",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.6360,
    lng: 127.2165,
    mapRegionId: "KR_GG_NAMYANGJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_DONGDUCHEON",
    name: "동두천",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.9036,
    lng: 127.0607,
    mapRegionId: "KR_GG_DONGDUCHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_YANGJU",
    name: "양주",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.7852,
    lng: 127.0458,
    mapRegionId: "KR_GG_YANGJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_POCHEON",
    name: "포천",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.8949,
    lng: 127.2003,
    mapRegionId: "KR_GG_POCHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_ICHEON",
    name: "이천",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.2720,
    lng: 127.4350,
    mapRegionId: "KR_GG_ICHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_ANSEONG",
    name: "안성",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.0081,
    lng: 127.2799,
    mapRegionId: "KR_GG_ANSEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_OSAN",
    name: "오산",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.1498,
    lng: 127.0772,
    mapRegionId: "KR_GG_OSAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_HANAM",
    name: "하남",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.5393,
    lng: 127.2149,
    mapRegionId: "KR_GG_HANAM",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_UWANG",
    name: "의왕",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.3446,
    lng: 126.9687,
    mapRegionId: "KR_GG_UWANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_YEOJU",
    name: "여주",
    province: "경기도",
    type: KoreaRegionType.city,
    lat: 37.2982,
    lng: 127.6373,
    mapRegionId: "KR_GG_YEOJU",
    mapRegionType: MapRegionType.city,
  ),

  // ===== 군 =====
  KoreaRegion(
    id: "KR_GG_YEONCHEON",
    name: "연천",
    province: "경기도",
    type: KoreaRegionType.county,
    lat: 38.0966,
    lng: 127.0748,
    mapRegionId: "KR_GG_YEONCHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_GAPYEONG",
    name: "가평",
    province: "경기도",
    type: KoreaRegionType.county,
    lat: 37.8315,
    lng: 127.5106,
    mapRegionId: "KR_GG_GAPYEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_GG_YANGPYEONG",
    name: "양평",
    province: "경기도",
    type: KoreaRegionType.county,
    lat: 37.4910,
    lng: 127.4875,
    mapRegionId: "KR_GG_YANGPYEONG",
    mapRegionType: MapRegionType.city,
  ),
];
