import 'korea_region.dart';

const List<KoreaRegion> jeonnamRegions = [
  // ===== 시 =====
  KoreaRegion(
    id: "KR_JN_MOKPO",
    name: "목포",
    nameEn: "MOKPO",
    province: "전라남도",
    type: KoreaRegionType.city,
    lat: 34.8118,
    lng: 126.3922,
    mapRegionId: "KR_JN_MOKPO",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_YEOSU",
    name: "여수",
    nameEn: "YEOSU",
    province: "전라남도",
    type: KoreaRegionType.city,
    lat: 34.7604,
    lng: 127.6622,
    mapRegionId: "KR_JN_YEOSU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_SUNCHEON",
    name: "순천",
    nameEn: "SUNCHEON",
    province: "전라남도",
    type: KoreaRegionType.city,
    lat: 34.9507,
    lng: 127.4872,
    mapRegionId: "KR_JN_SUNCHEON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_NAJU",
    name: "나주",
    nameEn: "NAJU",
    province: "전라남도",
    type: KoreaRegionType.city,
    lat: 35.0159,
    lng: 126.7108,
    mapRegionId: "KR_JN_NAJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_GWANGYANG",
    name: "광양",
    nameEn: "GWANGYANG",
    province: "전라남도",
    type: KoreaRegionType.city,
    lat: 34.9407,
    lng: 127.6959,
    mapRegionId: "KR_JN_GWANGYANG",
    mapRegionType: MapRegionType.city,
  ),

  // ===== 군 =====
  KoreaRegion(
    id: "KR_JN_DAMYANG",
    name: "담양",
    nameEn: "DAMYANG",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 35.3215,
    lng: 126.9882,
    mapRegionId: "KR_JN_DAMYANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_GOKSEONG",
    name: "곡성",
    nameEn: "GOKSEONG",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 35.2816,
    lng: 127.2921,
    mapRegionId: "KR_JN_GOKSEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_GURYE",
    name: "구례",
    nameEn: "GURYE",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 35.2020,
    lng: 127.4628,
    mapRegionId: "KR_JN_GURYE",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_GOHEUNG",
    name: "고흥",
    nameEn: "GOHEUNG",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 34.6106,
    lng: 127.2858,
    mapRegionId: "KR_JN_GOHEUNG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_BOSEONG",
    name: "보성",
    nameEn: "BOSEONG",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 34.7714,
    lng: 127.0802,
    mapRegionId: "KR_JN_BOSEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_HWASUN",
    name: "화순",
    nameEn: "HWASUN",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 35.0615,
    lng: 126.9876,
    mapRegionId: "KR_JN_HWASUN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_JANGHEUNG",
    name: "장흥",
    nameEn: "JANGHEUNG",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 34.6814,
    lng: 126.9071,
    mapRegionId: "KR_JN_JANGHEUNG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_GANGJIN",
    name: "강진",
    nameEn: "GANGJIN",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 34.6421,
    lng: 126.7672,
    mapRegionId: "KR_JN_GANGJIN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_HAENAM",
    name: "해남",
    nameEn: "HAENAM",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 34.5733,
    lng: 126.5989,
    mapRegionId: "KR_JN_HAENAM",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_YEONGAM",
    name: "영암",
    nameEn: "YEONGAM",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 34.8002,
    lng: 126.6969,
    mapRegionId: "KR_JN_YEONGAM",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_MUAN",
    name: "무안",
    nameEn: "MUAN",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 34.9904,
    lng: 126.4788,
    mapRegionId: "KR_JN_MUAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_HAMPYEONG",
    name: "함평",
    nameEn: "HAMPYEONG",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 35.0658,
    lng: 126.5166,
    mapRegionId: "KR_JN_HAMPYEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_YEONGGWANG",
    name: "영광",
    nameEn: "YEONGGWANG",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 35.2771,
    lng: 126.5124,
    mapRegionId: "KR_JN_YEONGGWANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_JANGSEONG",
    name: "장성",
    nameEn: "JANGSEONG",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 35.3019,
    lng: 126.7845,
    mapRegionId: "KR_JN_JANGSEONG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_WANDO",
    name: "완도",
    nameEn: "WANDO",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 34.3119,
    lng: 126.7551,
    mapRegionId: "KR_JN_WANDO",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_JINDO",
    name: "진도",
    nameEn: "JINDO",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 34.4869,
    lng: 126.2635,
    mapRegionId: "KR_JN_JINDO",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JN_SINAN",
    name: "신안",
    nameEn: "SINAN",
    province: "전라남도",
    type: KoreaRegionType.county,
    lat: 34.8336,
    lng: 126.0997,
    mapRegionId: "KR_JN_SINAN",
    mapRegionType: MapRegionType.city,
  ),
];
