import 'korea_region.dart';

const List<KoreaRegion> jeonbukRegions = [
  // ===== 시 =====
  KoreaRegion(
    id: "KR_JB_JEONJU",
    name: "전주",
    province: "전라북도",
    type: KoreaRegionType.city,
    lat: 35.8242,
    lng: 127.1480,
    mapRegionId: "KR_JB_JEONJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JB_GUNSAN",
    name: "군산",
    province: "전라북도",
    type: KoreaRegionType.city,
    lat: 35.9677,
    lng: 126.7366,
    mapRegionId: "KR_JB_GUNSAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JB_IKSAN",
    name: "익산",
    province: "전라북도",
    type: KoreaRegionType.city,
    lat: 35.9483,
    lng: 126.9576,
    mapRegionId: "KR_JB_IKSAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JB_JEONGEUP",
    name: "정읍",
    province: "전라북도",
    type: KoreaRegionType.city,
    lat: 35.5699,
    lng: 126.8556,
    mapRegionId: "KR_JB_JEONGEUP",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JB_NAMWON",
    name: "남원",
    province: "전라북도",
    type: KoreaRegionType.city,
    lat: 35.4164,
    lng: 127.3906,
    mapRegionId: "KR_JB_NAMWON",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JB_GIMJE",
    name: "김제",
    province: "전라북도",
    type: KoreaRegionType.city,
    lat: 35.8036,
    lng: 126.8800,
    mapRegionId: "KR_JB_GIMJE",
    mapRegionType: MapRegionType.city,
  ),

  // ===== 군 =====
  KoreaRegion(
    id: "KR_JB_WANJU",
    name: "완주",
    province: "전라북도",
    type: KoreaRegionType.county,
    lat: 35.9053,
    lng: 127.1626,
    mapRegionId: "KR_JB_WANJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JB_JINAN",
    name: "진안",
    province: "전라북도",
    type: KoreaRegionType.county,
    lat: 35.7916,
    lng: 127.4247,
    mapRegionId: "KR_JB_JINAN",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JB_MUJU",
    name: "무주",
    province: "전라북도",
    type: KoreaRegionType.county,
    lat: 36.0074,
    lng: 127.6611,
    mapRegionId: "KR_JB_MUJU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JB_JANGSU",
    name: "장수",
    province: "전라북도",
    type: KoreaRegionType.county,
    lat: 35.6443,
    lng: 127.5200,
    mapRegionId: "KR_JB_JANGSU",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JB_IMSIL",
    name: "임실",
    province: "전라북도",
    type: KoreaRegionType.county,
    lat: 35.6178,
    lng: 127.2886,
    mapRegionId: "KR_JB_IMSIL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JB_SUNCHANG",
    name: "순창",
    province: "전라북도",
    type: KoreaRegionType.county,
    lat: 35.3745,
    lng: 127.1375,
    mapRegionId: "KR_JB_SUNCHANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JB_GOCHANG",
    name: "고창",
    province: "전라북도",
    type: KoreaRegionType.county,
    lat: 35.4358,
    lng: 126.7020,
    mapRegionId: "KR_JB_GOCHANG",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_JB_BUAN",
    name: "부안",
    province: "전라북도",
    type: KoreaRegionType.county,
    lat: 35.7318,
    lng: 126.7339,
    mapRegionId: "KR_JB_BUAN",
    mapRegionType: MapRegionType.city,
  ),
];
