import 'korea_region.dart';

const List<KoreaRegion> koreaRegionMaster = [
  // =========================
  // 특별시 / 광역시 / 세종
  // =========================
  KoreaRegion(
    id: 'KR_SEOUL',
    name: '서울',
    province: '서울특별시',
    type: KoreaRegionType.city,
    lat: 37.5665,
    lng: 126.9780,
    mapRegionId: 'KR_SEOUL',
    mapRegionType: MapRegionType.metro,
  ),
  KoreaRegion(
    id: 'KR_BUSAN',
    name: '부산',
    province: '부산광역시',
    type: KoreaRegionType.city,
    lat: 35.1796,
    lng: 129.0756,
    mapRegionId: 'KR_BUSAN',
    mapRegionType: MapRegionType.metro,
  ),
  KoreaRegion(
    id: 'KR_DAEGU',
    name: '대구',
    province: '대구광역시',
    type: KoreaRegionType.city,
    lat: 35.8714,
    lng: 128.6014,
    mapRegionId: 'KR_DAEGU',
    mapRegionType: MapRegionType.metro,
  ),
  KoreaRegion(
    id: 'KR_INCHEON',
    name: '인천',
    province: '인천광역시',
    type: KoreaRegionType.city,
    lat: 37.4563,
    lng: 126.7052,
    mapRegionId: 'KR_INCHEON',
    mapRegionType: MapRegionType.metro,
  ),
  KoreaRegion(
    id: 'KR_GWANGJU',
    name: '광주',
    province: '광주광역시',
    type: KoreaRegionType.city,
    lat: 35.1595,
    lng: 126.8526,
    mapRegionId: 'KR_GWANGJU',
    mapRegionType: MapRegionType.metro,
  ),
  KoreaRegion(
    id: 'KR_DAEJEON',
    name: '대전',
    province: '대전광역시',
    type: KoreaRegionType.city,
    lat: 36.3504,
    lng: 127.3845,
    mapRegionId: 'KR_DAEJEON',
    mapRegionType: MapRegionType.metro,
  ),
  KoreaRegion(
    id: 'KR_ULSAN',
    name: '울산',
    province: '울산광역시',
    type: KoreaRegionType.city,
    lat: 35.5384,
    lng: 129.3114,
    mapRegionId: 'KR_ULSAN',
    mapRegionType: MapRegionType.metro,
  ),
  KoreaRegion(
    id: 'KR_SEJONG',
    name: '세종',
    province: '세종특별자치시',
    type: KoreaRegionType.city,
    lat: 36.4801,
    lng: 127.2890,
    mapRegionId: 'KR_SEJONG',
    mapRegionType: MapRegionType.metro,
  ),

  // =========================
  // 도
  // =========================
  KoreaRegion(
    id: 'KR_GYEONGGI',
    name: '경기',
    province: '경기도',
    type: KoreaRegionType.city,
    lat: 37.4138,
    lng: 127.5183,
    mapRegionId: 'KR_GYEONGGI',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GANGWON',
    name: '강원',
    province: '강원특별자치도',
    type: KoreaRegionType.city,
    lat: 37.8228,
    lng: 128.1555,
    mapRegionId: 'KR_GANGWON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CHUNGBUK',
    name: '충북',
    province: '충청북도',
    type: KoreaRegionType.city,
    lat: 36.6357,
    lng: 127.4917,
    mapRegionId: 'KR_CHUNGBUK',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CHUNGNAM',
    name: '충남',
    province: '충청남도',
    type: KoreaRegionType.city,
    lat: 36.5184,
    lng: 126.8000,
    mapRegionId: 'KR_CHUNGNAM',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JEONBUK',
    name: '전북',
    province: '전북특별자치도',
    type: KoreaRegionType.city,
    lat: 35.7175,
    lng: 127.1530,
    mapRegionId: 'KR_JEONBUK',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JEONNAM',
    name: '전남',
    province: '전라남도',
    type: KoreaRegionType.city,
    lat: 34.8679,
    lng: 126.9910,
    mapRegionId: 'KR_JEONNAM',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GYEONGBUK',
    name: '경북',
    province: '경상북도',
    type: KoreaRegionType.city,
    lat: 36.4919,
    lng: 128.8889,
    mapRegionId: 'KR_GYEONGBUK',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GYEONGNAM',
    name: '경남',
    province: '경상남도',
    type: KoreaRegionType.city,
    lat: 35.4606,
    lng: 128.2132,
    mapRegionId: 'KR_GYEONGNAM',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JEJU',
    name: '제주',
    province: '제주특별자치도',
    type: KoreaRegionType.city,
    lat: 33.4996,
    lng: 126.5312,
    mapRegionId: 'KR_JEJU',
    mapRegionType: MapRegionType.city,
  ),
  // =========================
  // 경기도 - 시
  // =========================
  KoreaRegion(
    id: 'KR_GG_SUWON',
    name: '수원',
    province: '경기도',
    type: KoreaRegionType.city,
    lat: 37.2636,
    lng: 127.0286,
    mapRegionId: 'KR_GG_SUWON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GG_SEONGNAM',
    name: '성남',
    province: '경기도',
    type: KoreaRegionType.city,
    lat: 37.4200,
    lng: 127.1265,
    mapRegionId: 'KR_GG_SEONGNAM',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GG_GOYANG',
    name: '고양',
    province: '경기도',
    type: KoreaRegionType.city,
    lat: 37.6584,
    lng: 126.8320,
    mapRegionId: 'KR_GG_GOYANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GG_YONGIN',
    name: '용인',
    province: '경기도',
    type: KoreaRegionType.city,
    lat: 37.2411,
    lng: 127.1776,
    mapRegionId: 'KR_GG_YONGIN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GG_BUCHEON',
    name: '부천',
    province: '경기도',
    type: KoreaRegionType.city,
    lat: 37.5036,
    lng: 126.7660,
    mapRegionId: 'KR_GG_BUCHEON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GG_ANSAN',
    name: '안산',
    province: '경기도',
    type: KoreaRegionType.city,
    lat: 37.3219,
    lng: 126.8309,
    mapRegionId: 'KR_GG_ANSAN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GG_ANYANG',
    name: '안양',
    province: '경기도',
    type: KoreaRegionType.city,
    lat: 37.3943,
    lng: 126.9568,
    mapRegionId: 'KR_GG_ANYANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GG_NAMYANGJU',
    name: '남양주',
    province: '경기도',
    type: KoreaRegionType.city,
    lat: 37.6360,
    lng: 127.2165,
    mapRegionId: 'KR_GG_NAMYANGJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GG_HWASEONG',
    name: '화성',
    province: '경기도',
    type: KoreaRegionType.city,
    lat: 37.1995,
    lng: 126.8310,
    mapRegionId: 'KR_GG_HWASEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GG_PYEONGTAEK',
    name: '평택',
    province: '경기도',
    type: KoreaRegionType.city,
    lat: 36.9923,
    lng: 127.1127,
    mapRegionId: 'KR_GG_PYEONGTAEK',
    mapRegionType: MapRegionType.city,
  ),

  // =========================
  // 경기도 - 군
  // =========================
  KoreaRegion(
    id: 'KR_GG_YEONCHEON',
    name: '연천',
    province: '경기도',
    type: KoreaRegionType.county,
    lat: 38.0964,
    lng: 127.0750,
    mapRegionId: 'KR_GG_YEONCHEON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GG_GAPYEONG',
    name: '가평',
    province: '경기도',
    type: KoreaRegionType.county,
    lat: 37.8315,
    lng: 127.5106,
    mapRegionId: 'KR_GG_GAPYEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GG_YANGPYEONG',
    name: '양평',
    province: '경기도',
    type: KoreaRegionType.county,
    lat: 37.4916,
    lng: 127.4876,
    mapRegionId: 'KR_GG_YANGPYEONG',
    mapRegionType: MapRegionType.city,
  ),
  // =========================
  // 경상북도 - 시
  // =========================
  KoreaRegion(
    id: 'KR_GB_POHANG',
    name: '포항',
    province: '경상북도',
    type: KoreaRegionType.city,
    lat: 36.0190,
    lng: 129.3435,
    mapRegionId: 'KR_GB_POHANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GB_GYEONGJU',
    name: '경주',
    province: '경상북도',
    type: KoreaRegionType.city,
    lat: 35.8562,
    lng: 129.2247,
    mapRegionId: 'KR_GB_GYEONGJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GB_GUMI',
    name: '구미',
    province: '경상북도',
    type: KoreaRegionType.city,
    lat: 36.1195,
    lng: 128.3446,
    mapRegionId: 'KR_GB_GUMI',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GB_ANDONG',
    name: '안동',
    province: '경상북도',
    type: KoreaRegionType.city,
    lat: 36.5684,
    lng: 128.7294,
    mapRegionId: 'KR_GB_ANDONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GB_YEONGJU',
    name: '영주',
    province: '경상북도',
    type: KoreaRegionType.city,
    lat: 36.8057,
    lng: 128.6240,
    mapRegionId: 'KR_GB_YEONGJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GB_SANGJU',
    name: '상주',
    province: '경상북도',
    type: KoreaRegionType.city,
    lat: 36.4109,
    lng: 128.1590,
    mapRegionId: 'KR_GB_SANGJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GB_MUNGYEONG',
    name: '문경',
    province: '경상북도',
    type: KoreaRegionType.city,
    lat: 36.5864,
    lng: 128.1869,
    mapRegionId: 'KR_GB_MUNGYEONG',
    mapRegionType: MapRegionType.city,
  ),

  // =========================
  // 경상북도 - 군
  // =========================
  KoreaRegion(
    id: 'KR_GB_YEONGYANG',
    name: '영양',
    province: '경상북도',
    type: KoreaRegionType.county,
    lat: 36.6667,
    lng: 129.1123,
    mapRegionId: 'KR_GB_YEONGYANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GB_CHEONGSONG',
    name: '청송',
    province: '경상북도',
    type: KoreaRegionType.county,
    lat: 36.4356,
    lng: 129.0570,
    mapRegionId: 'KR_GB_CHEONGSONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GB_BONGHWA',
    name: '봉화',
    province: '경상북도',
    type: KoreaRegionType.county,
    lat: 36.8932,
    lng: 128.7358,
    mapRegionId: 'KR_GB_BONGHWA',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GB_ULJIN',
    name: '울진',
    province: '경상북도',
    type: KoreaRegionType.county,
    lat: 36.9931,
    lng: 129.4000,
    mapRegionId: 'KR_GB_ULJIN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GB_ULLEUNG',
    name: '울릉',
    province: '경상북도',
    type: KoreaRegionType.county,
    lat: 37.4844,
    lng: 130.9057,
    mapRegionId: 'KR_SPECIAL_ULLEUNG',
    mapRegionType: MapRegionType.special,
  ),
  // =========================
  // 경상남도 - 시
  // =========================
  KoreaRegion(
    id: 'KR_GN_CHANGWON',
    name: '창원',
    province: '경상남도',
    type: KoreaRegionType.city,
    lat: 35.2286,
    lng: 128.6811,
    mapRegionId: 'KR_GN_CHANGWON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_JINJU',
    name: '진주',
    province: '경상남도',
    type: KoreaRegionType.city,
    lat: 35.1803,
    lng: 128.1076,
    mapRegionId: 'KR_GN_JINJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_TONGYEONG',
    name: '통영',
    province: '경상남도',
    type: KoreaRegionType.city,
    lat: 34.8544,
    lng: 128.4331,
    mapRegionId: 'KR_GN_TONGYEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_SACHEON',
    name: '사천',
    province: '경상남도',
    type: KoreaRegionType.city,
    lat: 35.0037,
    lng: 128.0646,
    mapRegionId: 'KR_GN_SACHEON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_GIMHAE',
    name: '김해',
    province: '경상남도',
    type: KoreaRegionType.city,
    lat: 35.2280,
    lng: 128.8890,
    mapRegionId: 'KR_GN_GIMHAE',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_MIRYANG',
    name: '밀양',
    province: '경상남도',
    type: KoreaRegionType.city,
    lat: 35.5039,
    lng: 128.7460,
    mapRegionId: 'KR_GN_MIRYANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_GEOJE',
    name: '거제',
    province: '경상남도',
    type: KoreaRegionType.city,
    lat: 34.8806,
    lng: 128.6210,
    mapRegionId: 'KR_GN_GEOJE',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_YANGSAN',
    name: '양산',
    province: '경상남도',
    type: KoreaRegionType.city,
    lat: 35.3350,
    lng: 129.0370,
    mapRegionId: 'KR_GN_YANGSAN',
    mapRegionType: MapRegionType.city,
  ),

  // =========================
  // 경상남도 - 군
  // =========================
  KoreaRegion(
    id: 'KR_GN_UIRYEONG',
    name: '의령',
    province: '경상남도',
    type: KoreaRegionType.county,
    lat: 35.3222,
    lng: 128.2616,
    mapRegionId: 'KR_GN_UIRYEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_HAMAN',
    name: '함안',
    province: '경상남도',
    type: KoreaRegionType.county,
    lat: 35.2726,
    lng: 128.4065,
    mapRegionId: 'KR_GN_HAMAN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_CHANGNYEONG',
    name: '창녕',
    province: '경상남도',
    type: KoreaRegionType.county,
    lat: 35.5446,
    lng: 128.4923,
    mapRegionId: 'KR_GN_CHANGNYEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_GOSEONG',
    name: '고성',
    province: '경상남도',
    type: KoreaRegionType.county,
    lat: 34.9731,
    lng: 128.3224,
    mapRegionId: 'KR_GN_GOSEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_NAMHAE',
    name: '남해',
    province: '경상남도',
    type: KoreaRegionType.county,
    lat: 34.8376,
    lng: 127.8924,
    mapRegionId: 'KR_GN_NAMHAE',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_HADONG',
    name: '하동',
    province: '경상남도',
    type: KoreaRegionType.county,
    lat: 35.0673,
    lng: 127.7512,
    mapRegionId: 'KR_GN_HADONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_SANCHEONG',
    name: '산청',
    province: '경상남도',
    type: KoreaRegionType.county,
    lat: 35.4156,
    lng: 127.8730,
    mapRegionId: 'KR_GN_SANCHEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_HAMYANG',
    name: '함양',
    province: '경상남도',
    type: KoreaRegionType.county,
    lat: 35.5204,
    lng: 127.7255,
    mapRegionId: 'KR_GN_HAMYANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_GEOCHANG',
    name: '거창',
    province: '경상남도',
    type: KoreaRegionType.county,
    lat: 35.6867,
    lng: 127.9095,
    mapRegionId: 'KR_GN_GEOCHANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GN_HAPCHEON',
    name: '합천',
    province: '경상남도',
    type: KoreaRegionType.county,
    lat: 35.5667,
    lng: 128.1658,
    mapRegionId: 'KR_GN_HAPCHEON',
    mapRegionType: MapRegionType.city,
  ),
  // =========================
  // 충청북도 - 시
  // =========================
  KoreaRegion(
    id: 'KR_CB_CHEONGJU',
    name: '청주',
    province: '충청북도',
    type: KoreaRegionType.city,
    lat: 36.6424,
    lng: 127.4890,
    mapRegionId: 'KR_CB_CHEONGJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CB_CHUNGJU',
    name: '충주',
    province: '충청북도',
    type: KoreaRegionType.city,
    lat: 36.9910,
    lng: 127.9260,
    mapRegionId: 'KR_CB_CHUNGJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CB_JECHEON',
    name: '제천',
    province: '충청북도',
    type: KoreaRegionType.city,
    lat: 37.1326,
    lng: 128.1909,
    mapRegionId: 'KR_CB_JECHEON',
    mapRegionType: MapRegionType.city,
  ),

  // =========================
  // 충청북도 - 군
  // =========================
  KoreaRegion(
    id: 'KR_CB_BOEUN',
    name: '보은',
    province: '충청북도',
    type: KoreaRegionType.county,
    lat: 36.4890,
    lng: 127.7296,
    mapRegionId: 'KR_CB_BOEUN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CB_OKCHEON',
    name: '옥천',
    province: '충청북도',
    type: KoreaRegionType.county,
    lat: 36.3063,
    lng: 127.5714,
    mapRegionId: 'KR_CB_OKCHEON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CB_YEONGDONG',
    name: '영동',
    province: '충청북도',
    type: KoreaRegionType.county,
    lat: 36.1750,
    lng: 127.7835,
    mapRegionId: 'KR_CB_YEONGDONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CB_JINCHEON',
    name: '진천',
    province: '충청북도',
    type: KoreaRegionType.county,
    lat: 36.8557,
    lng: 127.4350,
    mapRegionId: 'KR_CB_JINCHEON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CB_GOESEONG',
    name: '괴산',
    province: '충청북도',
    type: KoreaRegionType.county,
    lat: 36.8153,
    lng: 127.7868,
    mapRegionId: 'KR_CB_GOESEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CB_EUMSEONG',
    name: '음성',
    province: '충청북도',
    type: KoreaRegionType.county,
    lat: 36.9404,
    lng: 127.6907,
    mapRegionId: 'KR_CB_EUMSEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CB_DANYANG',
    name: '단양',
    province: '충청북도',
    type: KoreaRegionType.county,
    lat: 36.9845,
    lng: 128.3657,
    mapRegionId: 'KR_CB_DANYANG',
    mapRegionType: MapRegionType.city,
  ),
  // =========================
  // 충청남도 - 시
  // =========================
  KoreaRegion(
    id: 'KR_CN_CHEONAN',
    name: '천안',
    province: '충청남도',
    type: KoreaRegionType.city,
    lat: 36.8151,
    lng: 127.1139,
    mapRegionId: 'KR_CN_CHEONAN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_GONGJU',
    name: '공주',
    province: '충청남도',
    type: KoreaRegionType.city,
    lat: 36.4466,
    lng: 127.1190,
    mapRegionId: 'KR_CN_GONGJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_BORYEONG',
    name: '보령',
    province: '충청남도',
    type: KoreaRegionType.city,
    lat: 36.3333,
    lng: 126.6129,
    mapRegionId: 'KR_CN_BORYEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_ASAN',
    name: '아산',
    province: '충청남도',
    type: KoreaRegionType.city,
    lat: 36.7898,
    lng: 127.0022,
    mapRegionId: 'KR_CN_ASAN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_SEOSAN',
    name: '서산',
    province: '충청남도',
    type: KoreaRegionType.city,
    lat: 36.7847,
    lng: 126.4503,
    mapRegionId: 'KR_CN_SEOSAN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_NONSAN',
    name: '논산',
    province: '충청남도',
    type: KoreaRegionType.city,
    lat: 36.1872,
    lng: 127.0988,
    mapRegionId: 'KR_CN_NONSAN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_GYERYONG',
    name: '계룡',
    province: '충청남도',
    type: KoreaRegionType.city,
    lat: 36.2744,
    lng: 127.2490,
    mapRegionId: 'KR_CN_GYERYONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_DANGJIN',
    name: '당진',
    province: '충청남도',
    type: KoreaRegionType.city,
    lat: 36.8890,
    lng: 126.6459,
    mapRegionId: 'KR_CN_DANGJIN',
    mapRegionType: MapRegionType.city,
  ),

  // =========================
  // 충청남도 - 군
  // =========================
  KoreaRegion(
    id: 'KR_CN_GEUMSAN',
    name: '금산',
    province: '충청남도',
    type: KoreaRegionType.county,
    lat: 36.1080,
    lng: 127.4889,
    mapRegionId: 'KR_CN_GEUMSAN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_BUYEO',
    name: '부여',
    province: '충청남도',
    type: KoreaRegionType.county,
    lat: 36.2759,
    lng: 126.9098,
    mapRegionId: 'KR_CN_BUYEO',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_SEOCHEON',
    name: '서천',
    province: '충청남도',
    type: KoreaRegionType.county,
    lat: 36.0801,
    lng: 126.6918,
    mapRegionId: 'KR_CN_SEOCHEON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_CHEONGYANG',
    name: '청양',
    province: '충청남도',
    type: KoreaRegionType.county,
    lat: 36.4593,
    lng: 126.8020,
    mapRegionId: 'KR_CN_CHEONGYANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_HONGSEONG',
    name: '홍성',
    province: '충청남도',
    type: KoreaRegionType.county,
    lat: 36.6010,
    lng: 126.6609,
    mapRegionId: 'KR_CN_HONGSEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_YESAN',
    name: '예산',
    province: '충청남도',
    type: KoreaRegionType.county,
    lat: 36.6826,
    lng: 126.8489,
    mapRegionId: 'KR_CN_YESAN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_CN_TAEAN',
    name: '태안',
    province: '충청남도',
    type: KoreaRegionType.county,
    lat: 36.7456,
    lng: 126.2986,
    mapRegionId: 'KR_CN_TAEAN',
    mapRegionType: MapRegionType.city,
  ),
  // =========================
  // 전라북도 - 시
  // =========================
  KoreaRegion(
    id: 'KR_JB_JEONJU',
    name: '전주',
    province: '전북특별자치도',
    type: KoreaRegionType.city,
    lat: 35.8242,
    lng: 127.1480,
    mapRegionId: 'KR_JB_JEONJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JB_GUNSAN',
    name: '군산',
    province: '전북특별자치도',
    type: KoreaRegionType.city,
    lat: 35.9677,
    lng: 126.7366,
    mapRegionId: 'KR_JB_GUNSAN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JB_IKSAN',
    name: '익산',
    province: '전북특별자치도',
    type: KoreaRegionType.city,
    lat: 35.9483,
    lng: 126.9578,
    mapRegionId: 'KR_JB_IKSAN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JB_JEONGEUP',
    name: '정읍',
    province: '전북특별자치도',
    type: KoreaRegionType.city,
    lat: 35.5699,
    lng: 126.8556,
    mapRegionId: 'KR_JB_JEONGEUP',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JB_NAMWON',
    name: '남원',
    province: '전북특별자치도',
    type: KoreaRegionType.city,
    lat: 35.4164,
    lng: 127.3904,
    mapRegionId: 'KR_JB_NAMWON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JB_GIMJE',
    name: '김제',
    province: '전북특별자치도',
    type: KoreaRegionType.city,
    lat: 35.8036,
    lng: 126.8800,
    mapRegionId: 'KR_JB_GIMJE',
    mapRegionType: MapRegionType.city,
  ),

  // =========================
  // 전라북도 - 군
  // =========================
  KoreaRegion(
    id: 'KR_JB_WANJU',
    name: '완주',
    province: '전북특별자치도',
    type: KoreaRegionType.county,
    lat: 35.9040,
    lng: 127.1625,
    mapRegionId: 'KR_JB_WANJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JB_JINAN',
    name: '진안',
    province: '전북특별자치도',
    type: KoreaRegionType.county,
    lat: 35.7917,
    lng: 127.4240,
    mapRegionId: 'KR_JB_JINAN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JB_MUJU',
    name: '무주',
    province: '전북특별자치도',
    type: KoreaRegionType.county,
    lat: 36.0070,
    lng: 127.6626,
    mapRegionId: 'KR_JB_MUJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JB_JANGSU',
    name: '장수',
    province: '전북특별자치도',
    type: KoreaRegionType.county,
    lat: 35.6446,
    lng: 127.5207,
    mapRegionId: 'KR_JB_JANGSU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JB_IMSIL',
    name: '임실',
    province: '전북특별자치도',
    type: KoreaRegionType.county,
    lat: 35.6179,
    lng: 127.2896,
    mapRegionId: 'KR_JB_IMSIL',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JB_SUNCHANG',
    name: '순창',
    province: '전북특별자치도',
    type: KoreaRegionType.county,
    lat: 35.3745,
    lng: 127.1376,
    mapRegionId: 'KR_JB_SUNCHANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JB_GOCHANG',
    name: '고창',
    province: '전북특별자치도',
    type: KoreaRegionType.county,
    lat: 35.4358,
    lng: 126.7019,
    mapRegionId: 'KR_JB_GOCHANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JB_BUAN',
    name: '부안',
    province: '전북특별자치도',
    type: KoreaRegionType.county,
    lat: 35.7318,
    lng: 126.7335,
    mapRegionId: 'KR_JB_BUAN',
    mapRegionType: MapRegionType.city,
  ),
  // =========================
  // 전라남도 - 시
  // =========================
  KoreaRegion(
    id: 'KR_JN_MOKPO',
    name: '목포',
    province: '전라남도',
    type: KoreaRegionType.city,
    lat: 34.8118,
    lng: 126.3922,
    mapRegionId: 'KR_JN_MOKPO',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_YEOSU',
    name: '여수',
    province: '전라남도',
    type: KoreaRegionType.city,
    lat: 34.7604,
    lng: 127.6622,
    mapRegionId: 'KR_JN_YEOSU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_SUNCHEON',
    name: '순천',
    province: '전라남도',
    type: KoreaRegionType.city,
    lat: 34.9506,
    lng: 127.4875,
    mapRegionId: 'KR_JN_SUNCHEON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_NAJU',
    name: '나주',
    province: '전라남도',
    type: KoreaRegionType.city,
    lat: 35.0158,
    lng: 126.7108,
    mapRegionId: 'KR_JN_NAJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_GWANGYANG',
    name: '광양',
    province: '전라남도',
    type: KoreaRegionType.city,
    lat: 34.9407,
    lng: 127.6959,
    mapRegionId: 'KR_JN_GWANGYANG',
    mapRegionType: MapRegionType.city,
  ),

  // =========================
  // 전라남도 - 군
  // =========================
  KoreaRegion(
    id: 'KR_JN_DAMYANG',
    name: '담양',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 35.3215,
    lng: 126.9881,
    mapRegionId: 'KR_JN_DAMYANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_GOKSEONG',
    name: '곡성',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 35.2820,
    lng: 127.2915,
    mapRegionId: 'KR_JN_GOKSEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_GURYE',
    name: '구례',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 35.2026,
    lng: 127.4626,
    mapRegionId: 'KR_JN_GURYE',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_GOHEUNG',
    name: '고흥',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 34.6113,
    lng: 127.2858,
    mapRegionId: 'KR_JN_GOHEUNG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_BOSEONG',
    name: '보성',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 34.7714,
    lng: 127.0800,
    mapRegionId: 'KR_JN_BOSEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_HWASUN',
    name: '화순',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 35.0626,
    lng: 126.9876,
    mapRegionId: 'KR_JN_HWASUN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_JANGHEUNG',
    name: '장흥',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 34.6816,
    lng: 126.9073,
    mapRegionId: 'KR_JN_JANGHEUNG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_GANGJIN',
    name: '강진',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 34.6421,
    lng: 126.7671,
    mapRegionId: 'KR_JN_GANGJIN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_HAENAM',
    name: '해남',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 34.5734,
    lng: 126.5986,
    mapRegionId: 'KR_JN_HAENAM',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_YEONGAM',
    name: '영암',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 34.8002,
    lng: 126.6967,
    mapRegionId: 'KR_JN_YEONGAM',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_MUAN',
    name: '무안',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 34.9904,
    lng: 126.4786,
    mapRegionId: 'KR_JN_MUAN',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_HAMPYEONG',
    name: '함평',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 35.0659,
    lng: 126.5166,
    mapRegionId: 'KR_JN_HAMPYEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_YEONGGWANG',
    name: '영광',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 35.2772,
    lng: 126.5116,
    mapRegionId: 'KR_JN_YEONGGWANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_JANGSEONG',
    name: '장성',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 35.3019,
    lng: 126.7847,
    mapRegionId: 'KR_JN_JANGSEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_WANDO',
    name: '완도',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 34.3119,
    lng: 126.7556,
    mapRegionId: 'KR_JN_WANDO',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_JINDO',
    name: '진도',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 34.4868,
    lng: 126.2635,
    mapRegionId: 'KR_JN_JINDO',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JN_SINAN',
    name: '신안',
    province: '전라남도',
    type: KoreaRegionType.county,
    lat: 34.8270,
    lng: 126.1072,
    mapRegionId: 'KR_JN_SINAN',
    mapRegionType: MapRegionType.city,
  ),
  // =========================
  // 강원특별자치도 - 시
  // =========================
  KoreaRegion(
    id: 'KR_GW_CHUNCHEON',
    name: '춘천',
    province: '강원특별자치도',
    type: KoreaRegionType.city,
    lat: 37.8813,
    lng: 127.7298,
    mapRegionId: 'KR_GW_CHUNCHEON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_WONJU',
    name: '원주',
    province: '강원특별자치도',
    type: KoreaRegionType.city,
    lat: 37.3422,
    lng: 127.9202,
    mapRegionId: 'KR_GW_WONJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_GANGNEUNG',
    name: '강릉',
    province: '강원특별자치도',
    type: KoreaRegionType.city,
    lat: 37.7519,
    lng: 128.8761,
    mapRegionId: 'KR_GW_GANGNEUNG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_DONGHAE',
    name: '동해',
    province: '강원특별자치도',
    type: KoreaRegionType.city,
    lat: 37.5247,
    lng: 129.1143,
    mapRegionId: 'KR_GW_DONGHAE',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_TAEBAEK',
    name: '태백',
    province: '강원특별자치도',
    type: KoreaRegionType.city,
    lat: 37.1641,
    lng: 128.9856,
    mapRegionId: 'KR_GW_TAEBAEK',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_SOKCHO',
    name: '속초',
    province: '강원특별자치도',
    type: KoreaRegionType.city,
    lat: 38.2070,
    lng: 128.5918,
    mapRegionId: 'KR_GW_SOKCHO',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_SAMCHEOK',
    name: '삼척',
    province: '강원특별자치도',
    type: KoreaRegionType.city,
    lat: 37.4499,
    lng: 129.1656,
    mapRegionId: 'KR_GW_SAMCHEOK',
    mapRegionType: MapRegionType.city,
  ),

  // =========================
  // 강원특별자치도 - 군
  // =========================
  KoreaRegion(
    id: 'KR_GW_HONGCHEON',
    name: '홍천',
    province: '강원특별자치도',
    type: KoreaRegionType.county,
    lat: 37.6973,
    lng: 127.8886,
    mapRegionId: 'KR_GW_HONGCHEON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_HOENGSEONG',
    name: '횡성',
    province: '강원특별자치도',
    type: KoreaRegionType.county,
    lat: 37.4914,
    lng: 127.9847,
    mapRegionId: 'KR_GW_HOENGSEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_YEONGWOL',
    name: '영월',
    province: '강원특별자치도',
    type: KoreaRegionType.county,
    lat: 37.1834,
    lng: 128.4610,
    mapRegionId: 'KR_GW_YEONGWOL',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_PYEONGCHANG',
    name: '평창',
    province: '강원특별자치도',
    type: KoreaRegionType.county,
    lat: 37.3703,
    lng: 128.3907,
    mapRegionId: 'KR_GW_PYEONGCHANG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_JEONGSEON',
    name: '정선',
    province: '강원특별자치도',
    type: KoreaRegionType.county,
    lat: 37.3806,
    lng: 128.6609,
    mapRegionId: 'KR_GW_JEONGSEON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_CHEORWON',
    name: '철원',
    province: '강원특별자치도',
    type: KoreaRegionType.county,
    lat: 38.1466,
    lng: 127.3133,
    mapRegionId: 'KR_GW_CHEORWON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_HWACHEON',
    name: '화천',
    province: '강원특별자치도',
    type: KoreaRegionType.county,
    lat: 38.1060,
    lng: 127.7089,
    mapRegionId: 'KR_GW_HWACHEON',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_YANGGU',
    name: '양구',
    province: '강원특별자치도',
    type: KoreaRegionType.county,
    lat: 38.1099,
    lng: 127.9896,
    mapRegionId: 'KR_GW_YANGGU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_INJE',
    name: '인제',
    province: '강원특별자치도',
    type: KoreaRegionType.county,
    lat: 38.0690,
    lng: 128.1705,
    mapRegionId: 'KR_GW_INJE',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_GOSEONG',
    name: '고성',
    province: '강원특별자치도',
    type: KoreaRegionType.county,
    lat: 38.3806,
    lng: 128.4679,
    mapRegionId: 'KR_GW_GOSEONG',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_GW_YANGYANG',
    name: '양양',
    province: '강원특별자치도',
    type: KoreaRegionType.county,
    lat: 38.0750,
    lng: 128.6192,
    mapRegionId: 'KR_GW_YANGYANG',
    mapRegionType: MapRegionType.city,
  ),
  // =========================
  // 제주특별자치도 - 시
  // =========================
  KoreaRegion(
    id: 'KR_JEJU_JEJU',
    name: '제주',
    province: '제주특별자치도',
    type: KoreaRegionType.city,
    lat: 33.4996,
    lng: 126.5312,
    mapRegionId: 'KR_JEJU_JEJU',
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: 'KR_JEJU_SEOGWIPO',
    name: '서귀포',
    province: '제주특별자치도',
    type: KoreaRegionType.city,
    lat: 33.2541,
    lng: 126.5601,
    mapRegionId: 'KR_JEJU_SEOGWIPO',
    mapRegionType: MapRegionType.city,
  ),

  // =========================
  // 특수지역
  // =========================
  KoreaRegion(
    id: 'KR_SPECIAL_ULLEUNG',
    name: '울릉도',
    province: '경상북도',
    type: KoreaRegionType.county,
    lat: 37.4844,
    lng: 130.9057,
    mapRegionId: 'KR_SPECIAL_ULLEUNG',
    mapRegionType: MapRegionType.special,
  ),
  KoreaRegion(
    id: 'KR_SPECIAL_DOKDO',
    name: '독도',
    province: '경상북도',
    type: KoreaRegionType.county,
    lat: 37.2429,
    lng: 131.8645,
    mapRegionId: 'KR_SPECIAL_DOKDO',
    mapRegionType: MapRegionType.special,
  ),
];
