import 'korea_region.dart';

const List<KoreaRegion> seoulRegions = [
  KoreaRegion(
    id: "KR_SEOUL_JONGNO",
    name: "종로",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_JUNG",
    name: "중구",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_YONGSAN",
    name: "용산",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_SEONGDONG",
    name: "성동",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GWANGJIN",
    name: "광진",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_DONGDAEMUN",
    name: "동대문",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_JUNGNANG",
    name: "중랑",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_SEONGBUK",
    name: "성북",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GANGBUK",
    name: "강북",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_DOBONG",
    name: "도봉",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_NOWON",
    name: "노원",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_EUNPYEONG",
    name: "은평",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_SEODAEMUN",
    name: "서대문",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_MAPO",
    name: "마포",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_YANGCHEON",
    name: "양천",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GANGSEO",
    name: "강서",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GURO",
    name: "구로",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GEUMCHEON",
    name: "금천",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_YEONGDEUNGPO",
    name: "영등포",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_DONGJAK",
    name: "동작",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GWANAK",
    name: "관악",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_SEOCHO",
    name: "서초",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GANGNAM",
    name: "강남",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_SONGPA",
    name: "송파",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GANGDONG",
    name: "강동",
    province: "서울특별시",
    type: KoreaRegionType.city,
  ),
];
