import 'korea_region.dart';

const List<KoreaRegion> seoulRegions = [
  KoreaRegion(
    id: "KR_SEOUL_JONGNO",
    name: "종로",
    nameEn: "JONGNO",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5729,
    lng: 126.9794,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_JUNG",
    name: "중구",
    nameEn: "JUNG",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5636,
    lng: 126.9976,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_YONGSAN",
    name: "용산",
    nameEn: "YONGSAN",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5326,
    lng: 126.9906,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_SEONGDONG",
    name: "성동",
    nameEn: "SEONGDONG",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5634,
    lng: 127.0369,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GWANGJIN",
    name: "광진",
    nameEn: "GWANGJIN",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5385,
    lng: 127.0823,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_DONGDAEMUN",
    name: "동대문",
    nameEn: "DONGDAEMUN",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5744,
    lng: 127.0396,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_JUNGNANG",
    name: "중랑",
    nameEn: "JUNGNANG",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.6066,
    lng: 127.0926,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_SEONGBUK",
    name: "성북",
    nameEn: "SEONGBUK",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5894,
    lng: 127.0167,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GANGBUK",
    name: "강북",
    nameEn: "GANGBUK",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.6396,
    lng: 127.0257,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_DOBONG",
    name: "도봉",
    nameEn: "DOBONG",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.6688,
    lng: 127.0471,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_NOWON",
    name: "노원",
    nameEn: "NOWON",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.6542,
    lng: 127.0568,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_EUNPYEONG",
    name: "은평",
    nameEn: "EUNPYEONG",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.6176,
    lng: 126.9227,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_SEODAEMUN",
    name: "서대문",
    nameEn: "SEODAEMUN",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5792,
    lng: 126.9368,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_MAPO",
    name: "마포",
    nameEn: "MAPO",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5663,
    lng: 126.9019,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_YANGCHEON",
    name: "양천",
    nameEn: "YANGCHEON",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5169,
    lng: 126.8666,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GANGSEO",
    name: "강서",
    nameEn: "GANGSEO",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5509,
    lng: 126.8496,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GURO",
    name: "구로",
    nameEn: "GURO",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.4955,
    lng: 126.8876,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GEUMCHEON",
    name: "금천",
    nameEn: "GEUMCHEON",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.4569,
    lng: 126.8955,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_YEONGDEUNGPO",
    name: "영등포",
    nameEn: "YEONGDEUNGPO",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5264,
    lng: 126.8963,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_DONGJAK",
    name: "동작",
    nameEn: "DONGJAK",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5124,
    lng: 126.9395,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GWANAK",
    name: "관악",
    nameEn: "GWANAK",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.4782,
    lng: 126.9516,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_SEOCHO",
    name: "서초",
    nameEn: "SEOCHO",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.4836,
    lng: 127.0327,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GANGNAM",
    name: "강남",
    nameEn: "GANGNAM",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5172,
    lng: 127.0473,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_SONGPA",
    name: "송파",
    nameEn: "SONGPA",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5145,
    lng: 127.1056,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
  KoreaRegion(
    id: "KR_SEOUL_GANGDONG",
    name: "강동",
    nameEn: "GANGDONG",
    province: "서울특별시",
    type: KoreaRegionType.city,
    lat: 37.5301,
    lng: 127.1238,
    mapRegionId: "KR_SEOUL",
    mapRegionType: MapRegionType.city,
  ),
];
