// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDRmwSnUBLZjHncU0uNCOlgmnPEdY0fcQ',
    appId: '1:277385353976:web:8f681c91f5188b2e27790d',
    messagingSenderId: '277385353976',
    projectId: 'travelmemoir-ee340',
    authDomain: 'travelmemoir-ee340.firebaseapp.com',
    storageBucket: 'travelmemoir-ee340.firebasestorage.app',
    measurementId: 'G-ZS5FHGR991',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa8JYa3_X8oWuv4fYWTRqowOhxCsn6dV4',
    appId: '1:277385353976:android:3ed1d136ef41c04b27790d',
    messagingSenderId: '277385353976',
    projectId: 'travelmemoir-ee340',
    storageBucket: 'travelmemoir-ee340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBN9chS0ExqIz3rNqv6jVfL7lFq3yRlUc',
    appId: '1:277385353976:ios:b32207bc2631ead727790d',
    messagingSenderId: '277385353976',
    projectId: 'travelmemoir-ee340',
    storageBucket: 'travelmemoir-ee340.firebasestorage.app',
    iosClientId: '277385353976-5807hspd33fcvloonsr814ra0559bsbe.apps.googleusercontent.com',
    iosBundleId: 'com.hanajungjun.travelmemoir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBN9chS0ExqIz3rNqv6jVfL7lFq3yRlUc',
    appId: '1:277385353976:ios:0a7436a7ab07f17327790d',
    messagingSenderId: '277385353976',
    projectId: 'travelmemoir-ee340',
    storageBucket: 'travelmemoir-ee340.firebasestorage.app',
    iosClientId: '277385353976-c9gu0lgn131lebo6o4dk6g3bhrejb5dj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDRmwSnUBLZjHncU0uNCOlgmnPEdY0fcQ',
    appId: '1:277385353976:web:b0f9839e21ea936c27790d',
    messagingSenderId: '277385353976',
    projectId: 'travelmemoir-ee340',
    authDomain: 'travelmemoir-ee340.firebaseapp.com',
    storageBucket: 'travelmemoir-ee340.firebasestorage.app',
    measurementId: 'G-2Z8TZR5R8Q',
  );
}
